### ISSUE TITLE
Duplicate Data in Select Fields

### ISSUE THREAD

**Issue by PiseAtharva** [chinh12hy/vue3-tags-input#3]
There seems to be a Duplicate Issue with the Select Fields(image attached), I can't diagnose this with Regex, how can we make this work correctly ?
![image](https://user-images.githubusercontent.com/88548999/210198543-ad82150e-206e-4c1f-b460-7c475cb81bdf.png)
![image](https://user-images.githubusercontent.com/88548999/210198560-6de8f161-50a5-4d9b-b4d7-a65bdd8e6704.png)

**Comment by chinh12hy** [comment]
> There seems to be a Duplicate Issue with the Select Fields(image attached), I can't diagnose this with Regex, how can we make this work correctly ? ![image](https://user-images.githubusercontent.com/88548999/210198543-ad82150e-206e-4c1f-b460-7c475cb81bdf.png) ![image](https://user-images.githubusercontent.com/88548999/210198560-6de8f161-50a5-4d9b-b4d7-a65bdd8e6704.png)

I will look into this bug and report back to you soon.

**Comment by chinh12hy** [comment]
> There seems to be a Duplicate Issue with the Select Fields(image attached), I can't diagnose this with Regex, how can we make this work correctly ? ![image](https://user-images.githubusercontent.com/88548999/210198543-ad82150e-206e-4c1f-b460-7c475cb81bdf.png) ![image](https://user-images.githubusercontent.com/88548999/210198560-6de8f161-50a5-4d9b-b4d7-a65bdd8e6704.png)

Now in the select items you need to add a unique field like `{ name: 'HTML', id: 1 }` and add one more props `:duplicate-select-item="false"` to fix your problem
