### ISSUE TITLE
Single Word Issue in Basic Tag Input

### ISSUE THREAD

**Issue by PiseAtharva** [chinh12hy/vue3-tags-input#4]
Whenever we press Spacebar, the tag is generated. If we can disable this or turn this as a boolean prop we can extend the usability for Multiple Word Tags for example **First Time Issue** or **Help Needed**.

Currently: Spacebar, Enter, and Comma Key will generate the tag with Basic Input.

Suitable Change: turn this into a prop (primarily false) and can be edited by Users to change for example - _disable-spacebar : true_

**Comment by marcorensch** [comment]
@PiseAtharva : See Docs - you can define which keys will trigger the add-tag: 
`:add-tag-on-keys="[13]"`
Will only add on "Enter" and you can use spacebars and comma in your tags

See: https://vue3-tags-input.netlify.app/documents
Default is 13, 188, 32 (Enter, comma, spacebar) as you mentioned

**Comment by PiseAtharva** [comment]
Hey thanks for your time, appreciate that really.
